version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    environment:
      - DATA_DRIVER=mock
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - .:/app
    networks:
      - classroom-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  classroom-network:
    driver: bridge
